### ISSUE TITLE
Omittig the ament_cmake when installing lgmath?

### ISSUE THREAD

**Issue by CodingCatMountain** [utiasASRL/lgmath#47]
Hi, developer! I wanne to ask a question about Could I omit the ament_cmake when installing lgmath? Cause I am a normal user of ROS1 Noetic, I don't have ament_cmake before. And When I try to install lgmath. I get an error in following:
"CMake Error at CMakeLists.txt:80 (find_package):
  By not providing "Findament_cmake.cmake" in CMAKE_MODULE_PATH this project
  has asked CMake to find a package configuration file provided by
  "ament_cmake", but CMake did not find one.

  Could not find a package configuration file provided by "ament_cmake" with
  any of the following names:

    ament_cmakeConfig.cmake
    ament_cmake-config.cmake

  Add the installation prefix of "ament_cmake" to CMAKE_PREFIX_PATH or set
  "ament_cmake_DIR" to a directory containing one of the above files.  If
  "ament_cmake" provides a separate development package or SDK, be sure it
  has been installed.
"

**Comment by keenan-burnett** [comment]
Yes, you can omit it. ament_cmake is for building in ROS2.
We've been using ROS2 exclusively for a while now, so we don't have a ready-to-use CMake file for building in ROS1. However, if you scroll back through our past commits, you'll see that we used to use ROS1.
Here's what the CMake file looked like before we started making changes:
https://github.com/utiasASRL/lgmath/blob/25c4e95e90047da59cc224f9b4b244b7d95e7d20/CMakeLists.txt

Perhaps you can modify the existing cmake file to look like the old one and build for ROS1.

**Comment by CodingCatMountain** [comment]
@keenan-burnett  Thank you, Keenan, I will try to modify CMake file. And One more question, Keenan, could you directly show me the corresponding code in the repo : ``steam`` or ``pysteam``  about GP prior which utilized the power-spectral density matrix? Because I just know about the normal GP with GRF as the kernel function, but be not familiar with the GP Prior mentioned in paper: <Full STEAM Ahead: Exactly Sparse Gaussian Process Regression for
Batch Continuous-Time Trajectory Estimation on SE(3)>.    :  )

**Comment by keenan-burnett** [comment]
The `Interface` class for constant velocity (white noise on acceleration) takes the diagonal of the power spectral density matrix $\mathbf{Q}_c$ as an argument:

https://github.com/utiasASRL/steam/blob/a17aff35cab6949f55fcd8c094c33b7ef3fb4f44/src/trajectory/const_vel/interface.cpp#L19

https://github.com/utiasASRL/pysteam/blob/c41bc1440d64051fdf5059373542f52cccf21d85/pysteam/trajectory/const_vel/interface.py#L35

**Comment by CodingCatMountain** [comment]
@keenan-burnett Thank you, Keenan!
